import { FITNESS_SVGS } from './svgs/fitness';
import { GENERAL_SVGS } from './svgs/general';

// ============================================================
// CUSTOM SVGS — Premium Stickman Set (Anti-Penyok)
// ============================================================

export const CUSTOM_SVGS: Record<string, string> = {
  ...FITNESS_SVGS,
  ...GENERAL_SVGS,
};

// ============================================================
// ICON MAP — ALIAS DRIVEN
// ============================================================

export const ICON_MAP: Record<string, string> = {
  // Categories
  'Latihan Fisik': 'mdi:arm-flex',
  'Belajar dan Refleksi': 'solar:library-bold',
  'Kerja dan Pertumbuhan': 'solar:rocket-2-bold',
  'Ketenangan Diri': 'mdi:meditation',
  'Beribadah': 'solar:heart-bold',
  'Kontrol Diri dan Rutinitas': 'solar:shield-star-bold',

  // Explicit Aliases
  LatihanFisik: 'mdi:arm-flex',
  BelajarRefleksi: 'solar:library-bold',
  KerjaPertumbuhan: 'solar:rocket-2-bold',
  KetenanganDiri: 'mdi:meditation',
  KontrolDiri: 'solar:shield-star-bold',

  // Habits
  'Cardio Session': 'custom:Treadmill',
  'Treadmill': 'custom:Treadmill',
  'Basketball': 'solar:basketball-bold',
  'Push-Ups': 'custom:PushUp',
  'PushUp': 'custom:PushUp',
  'PUSH-UPS': 'custom:PushUp',
  'Sit-Ups': 'custom:SitUp',
  'SitUp': 'custom:SitUp',
  'SIT-UPS': 'custom:SitUp',
  'Strength Training': 'custom:Weight',
  'WORK OUT': 'custom:Weight',
  'Weight': 'custom:Weight',
  'Skipping Rope': 'custom:Skipping',
  'Skipping': 'custom:Skipping',
  'Cycling': 'custom:Cycling',
  'Bike': 'custom:Cycling',
  'Deep Learning': 'solar:brain-2-bold',
  'Notebook': 'solar:brain-2-bold',
  'Reading': 'solar:book-2-bold',
  'News': 'solar:newspaper-bold',
  'Pages': 'solar:book-2-bold',
  'Journaling': 'solar:notebook-bold',
  'PenPaper': 'solar:pen-new-square-bold',
  'Language Learning': 'mdi:account-voice',
  'Voice': 'mdi:account-voice',
  'Research': 'solar:magnifer-bold',
  'Deep Work': 'custom:Working',
  'Monitor': 'solar:monitor-bold',
  'Meditation': 'mdi:meditation',
  'Meditate': 'mdi:meditation',
  'Music Practice': 'solar:music-note-bold',
  'MusicNote': 'solar:music-note-bold',
  'Spiritual': 'ph:hands-praying-bold',
  'Early Wake Up': 'solar:sunrise-bold',
  'Sunrise': 'solar:sunrise-bold',
  'Sleep Hygiene': 'solar:bed-bold',
  'Bed': 'solar:bed-bold',
  'Drink 2L Water': 'custom:WaterGlass',
  'WaterGlass': 'custom:WaterGlass',
  'Hydration': 'custom:WaterGlass',
  'Droplets': 'solar:water-drops-bold',
  'Vitamin Intake': 'custom:Vitamin',
  'Medicine': 'custom:Vitamin',
  'Skin Care': 'custom:Skincare',
  'Cosmetic': 'custom:Skincare',
  'Cleaning': 'custom:Cleaning',
  'Broom': 'custom:Cleaning',
  'No Smoking': 'custom:NoSmoking',
  'SmokingOff': 'custom:NoSmoking',
  'No Junk Food': 'custom:NoJunkFood',
  'FoodOff': 'custom:NoJunkFood',
  'Protein Intake': 'custom:Protein',
  'Meat': 'custom:Protein',
};

export const isCustomIcon = (iconStr: string) => iconStr?.startsWith('custom:');
export const getCustomIconKey = (iconStr: string) => iconStr?.replace('custom:', '');

export const HABIT_COLORS: Record<string, string> = {
  Basketball: '#F97316',
  Treadmill: '#EF4444',
  PushUp: '#00FF85',
  SitUp: '#FF0000',
  Weight: '#4F46E5',
  Protein: '#EF4444',
  Meat: '#EF4444',
  Activity: '#3B82F6',
  Bike: '#84CC16',
  Vitamin: '#8E44AD',
  Medicine: '#8E44AD',
  Pages: '#D97706',
  Cosmetic: '#EC4899',
  Voice: '#6ED7A0',
  Analysis: '#3B82F6',
  Briefcase: '#1F2937',
  MusicNote: '#C026D3',
  PhoneOff: '#6B7280',
  EyeOff: '#374151',
  Code: '#3B82F6',
  Bed: '#6366F1',
  PenPaper: '#6366F1',
  Brain: '#A855F7',
  Breathe: '#00FF85',
  Pray: '#FCD34D',
  Spiritual: '#FCD34D',
  Beribadah: '#FCD34D',
  Broom: '#38BDF8',
  SmokingOff: '#F43F5E',
  FoodOff: '#F43F5E',
  Sunrise: '#F59E0B',
  Droplets: '#3B82F6',
  Moon: '#6366F1',
  Heart: '#F43F5E',
  Fire: '#FF4D00',
  Skipping: '#EF4444',
  Research: '#3B82F6',
  Notebook: '#3B82F6',
  Library: '#D97706',
  Rocket: '#8E44AD',
  Cleaning: '#38BDF8',
  'No Smoking': '#F43F5E',
  'No Junk Food': '#F43F5E',
  'Early Wake Up': '#F59E0B',
  'Sleep Hygiene': '#6366F1',
  'Drink 2L Water': '#3B82F6',
  'WaterGlass': '#3B82F6',
  'Hydration': '#3B82F6',
  'Vitamin Intake': '#6ED7A0',
  'Skin Care': '#EC4899',
  'Protein Intake': '#F43F5E',
  'Deep Learning': '#06B6D4',
  'Reading': '#D97706',
  'News': '#F59E0B',
  'Journaling': '#6366F1',
  'Language Learning': '#6ED7A0',
  'Deep Work': '#06B6D4',
  'Breathing Exercise': '#00FF85',
  'Meditation': '#A855F7',
  'Music Practice': '#C026D3',
  'Cardio Session': '#F43F5E',
  'Push-Ups': '#00FF85',
  'Sit-Ups': '#3B82F6',
  'Strength Training': '#4F46E5',
  'Cycling': '#84CC16',
};
